version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.24
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ".env"

  app:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - "3000:3000"